Create basic front end
sayan-gg/gorapass-frontend pull request #3
Opened 2024-08-07 19:45 UTC by sayan-gg

This PR creates a basic front-end for GoraPass. It is able to send GET and POST requests to the backend server in order to get the stamps and filtered hike data.

2024-08-09 03:41 UTC, brandiseeley requested changes
Not super familiar with React yet, but looks good. The only issue is that this includes all of the `node_modules`. Those should be part of the `.gitignore`

2024-08-09 03:41 UTC, brandiseeley commented on node_modules/.bin/loose-envify
We should include all `node_modules` files in the `.gitignore`. Installing the node modules should be part of the setup instructions.

2024-08-10 14:49 UTC, sayan-gg commented on node_modules/.bin/loose-envify
Fixed this!

2024-08-10 14:49 UTC, sayan-gg commented
@brandiseeley ok, managed to fix that issue and the POST requests are working, so I think this is good to merge now.

2024-08-10 14:49 UTC, merged